# Generated by Django 2.2.6 on 2019-12-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
